### ISSUE TITLE
请问能否支持下微信小程序的webview呢

### ISSUE THREAD

**Issue by carryla** [feix760/WebViewDebugHook#2]
刚试用了一下，发现对微信（7.0.3）的小程序不起作用，请问能否支持下

**Comment by feix760** [comment]
我这边测试微信7.0.3 webview是可以正常hook的，你发一个url到聊天窗口点击打开试试
小程序不行，因为小程序没不在webview里运行，这个hook暂时不支持

**Comment by feix760** [comment]
已经支持了，你下最新的包试试，微信小程序是用 XWalkView 跑的

**Comment by carryla** [comment]
9.0微信小程序有进展吗
